### ISSUE TITLE
Changelog contains all changes

### ISSUE THREAD

**Issue by androideveloper** [bitrise-steplib/steps-generate-changelog#11]
This is not a bug report, but information for anyone, who has the same issue.. 
Recently Bitrise released a new major version of the git-clone Step which does not fetch tags by default (for speed)
https://github.com/bitrise-steplib/steps-git-clone/releases/tag/5.0.0
Generate-changelog step relies on tags, so you will need to enable them in git-clone step.
Hope this helps someone to save a bit of time 🙏

**Comment by mateherber** [comment]
Hi @androideveloper,

Thanks for clarifying this via this issue ticket. What is written above is indeed the case. Please set up the `git-clone` step's input accordingly for `generate-changelog` to work as intended!
