### ISSUE TITLE
failed to parse config

### ISSUE THREAD

**Issue by tobitech** [bitrise-steplib/steps-generate-changelog#7]
I'm getting this error. Is there a new version input I'm not setting?

Failed to parse configs, error: failed to parse config:
- NewVersion: required variable is not present

this is what i'm using for the Next Version field `$BITRISE_GIT_TAG`

**Comment by tobitech** [comment]
I changed this to `$XCODE_BUNDLE_VERSION` and it passed

**Comment by varyP** [comment]
@tobitech I have the same issue, switched to `$XCODE_BUNDLE_VERSION ` from `$BITRISE_GIT_TAG `, still getting the same error. Did you have to define the bundle version elsewhere on Bitrise?

**Comment by tobitech** [comment]
@varyP  I'm sorry I can't remember. I no longer work on the project and don't have access to the project's Bitrise account. I don't think I did, although I'm not sure.

**Comment by bitce** [comment]
Hi @varyP! Can you please submit here a URL for the build where this happens so we can look at the logs?

**Comment by varyP** [comment]
> Hi @varyP! Can you please submit here a URL for the build where this happens so we can look at the logs?

Here you go @bitce , is it accessible?
https://app.bitrise.io/build/5bf76acb7cf67bae#?tab=log

**Comment by teerayuthjanopas** [comment]
@bitce I got same error too
This is my logs
https://app.bitrise.io/build/1d456c15e7885b12#?tab=log

**Comment by teerayuthjanopas** [comment]
Hi @varyP I can figure it out by myself by Add step 'Get Xcode project version' Before 'Generate Changelog'
and fill Path to the 'info.plist'
And on 'Generate Changelog'
I use '$XBV_PROJECT_VERSION' instead '$BITRISE_GIT_TAG'

<img width="1036" alt="Screen Shot 2021-03-23 at 5 56 15 PM" src="https://user-images.githubusercontent.com/66584428/112136504-9e158b00-8c01-11eb-9687-7a008dd276fc.png">

<img width="945" alt="Screen Shot 2021-03-23 at 5 56 24 PM" src="https://user-images.githubusercontent.com/66584428/112136545-ab327a00-8c01-11eb-9338-add935b72936.png">
