### ISSUE TITLE
wrong changelog when tags are available

### ISSUE THREAD

**Issue by cbotsikas** [bitrise-steplib/steps-generate-changelog#9]
Based on [the code](https://github.com/bitrise-steplib/steps-generate-changelog/blob/master/main.go#L38-L43), when there are more than one tag, the changelog consists of the commits between the last two tags. This is fine, only if the last commit (or the commit the bitrise is invoked) has a tag, otherwise the changelog should contain all commits until the last tag (that's what is written in [the description](https://github.com/bitrise-steplib/steps-generate-changelog/blob/master/step.yml#L6)).

In my point of view there are the following schenarios:

- No tags: all commits
- One tag:
  - Tag is on checked out commit: all commits
  - Tag is on older commit: commits after the last tag
- More than one tag:
  - Last tag on checked out commit: commits between the last two commits, including the last one
  - Tags on older commits: commits after the last tag

**Comment by cbotsikas** [comment]
After two months, I can safely assume this issue and the pending PR got lost in the pile of work.
Any thoughts about this?

**Comment by bitce** [comment]
Sorry for the huge delay @cbotsikas! The PR is still in the team's backlog, I'll do what we can to bump to priority, but looking into this is definitely still on our plate.

**Comment by cbotsikas** [comment]
No problem @bitce, as long as you are aware of this, it's fine for me :). We are already using my forked step in our workflows so it's not a blocker for us.
